const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');
const root=path.resolve(process.env.SITE_ROOT||path.join(__dirname,'../site')),out=path.resolve(process.env.QA_OUTPUT||path.join(__dirname,'../qa'));fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.CHROME_EXECUTABLE?{executablePath:process.env.CHROME_EXECUTABLE}:{}),args:['--no-sandbox','--disable-dev-shm-usage']});const data=JSON.parse(fs.readFileSync(path.join(root,'data/index.json')));let checks=[],errors=[],missing=[],sources=[];
for(const width of [360,390,430]){const context=await browser.newContext({viewport:{width,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1,acceptDownloads:true});
let queueFixture=null;await context.route('**/*',async route=>{const url=new URL(route.request().url());let name=decodeURIComponent(url.pathname).replace(/^\//,'')||'index.html';if(name==='favicon.ico')return route.fulfill({status:204});if(name==='data/index.json'&&queueFixture)return route.fulfill({status:200,json:queueFixture});let file=path.resolve(root,name);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){missing.push(name);return route.fulfill({status:404,body:'missing'})}if(name.startsWith('media/source/'))sources.push(name);return route.fulfill({status:200,path:file,contentType:({'.html':'text/html','.css':'text/css','.js':'text/javascript','.json':'application/json','.jpg':'image/jpeg','.md':'text/markdown'})[path.extname(file)]||'application/octet-stream'})});
const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));const noOverflow=async(label)=>{const result=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert(result.scroll<=result.width,`${label}: horizontal overflow ${JSON.stringify(result)}`);checks.push(`${width}px ${label}: no overflow`)};
await page.goto('https://review.test/#overview');await page.getByRole('heading',{name:'Van krant naar inhoud'}).waitFor();await noOverflow('overview');assert.equal(sources.length,0,'full sources must not load on overview');if(width===390)await page.screenshot({path:path.join(out,'mobile-overview.png'),fullPage:true});
await page.getByRole('link',{name:'Edities',exact:true}).click();await page.locator('#results .card').first().waitFor();await noOverflow('editions');await page.locator('#filter-title').selectOption({label:data.editions[0].title});assert(await page.locator('#results .card').count()>0);await page.locator('#filter-text').fill('nonexistent-qa-query');await page.getByText('Geen edities met deze filters.').waitFor();await page.locator('#filter-text').fill('');
const p=data.pages.find(x=>x.units_count>0);await page.goto('https://review.test/#page/'+p.id);await page.getByRole('heading',{name:'Pagina '+p.page_number,exact:true}).waitFor();await page.locator('.viewer img').waitFor();await page.waitForFunction(()=>{const i=document.querySelector('.viewer img');return i?.complete&&i.naturalWidth>0});assert(await page.locator('.viewer img').evaluate(i=>i.complete&&i.naturalWidth>0));await noOverflow('page');await page.getByRole('button',{name:/Toon regio/}).click();assert.equal(await page.locator('#regions-overlay').getAttribute('hidden'),null);await page.getByRole('button',{name:/Toon regio/}).click();assert.notEqual(await page.locator('#regions-overlay').getAttribute('hidden'),null);await page.getByRole('button',{name:'Probleem',exact:true}).click();await page.locator('[data-note]').fill('QA-notitie: bron en OCR vergeleken.');await page.reload();await page.locator('[data-note]').waitFor();assert.equal(await page.locator('[data-note]').inputValue(),'QA-notitie: bron en OCR vergeleken.');assert.equal(await page.getByRole('button',{name:'Probleem',exact:true}).getAttribute('aria-pressed'),'true');checks.push(`${width}px persistentie reviewstatus + notitie`);
if(width===390)await page.screenshot({path:path.join(out,'mobile-page.png'),fullPage:true});
const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Deel antwoorden'}).click();const download=await downloadPromise;const save=path.join(out,`review-${width}.json`);await download.saveAs(save);const exported=JSON.parse(fs.readFileSync(save));assert(Object.values(exported.page_issue_notes).some(v=>v.note==='QA-notitie: bron en OCR vergeleken.'&&v.status==='problem'));checks.push(`${width}px JSON-export geverifieerd`);
await page.locator('.unit summary').first().click();const crop=page.locator('.unit-content .image-button').first();await crop.click();await page.locator('dialog[open]').waitFor();await page.waitForFunction(()=>{let x=document.getElementById('zoom-image');return x.complete&&x.naturalWidth>0});await noOverflow('zoom');await page.getByRole('button',{name:'Inzoomen',exact:true}).click();assert.equal(await page.locator('#zoom-image').evaluate(i=>i.style.width),'160%');await page.getByRole('button',{name:'Sluiten ×'}).click();checks.push(`${width}px source crop zoom + overlay`);
await page.goto('https://review.test/#issues');await page.getByRole('heading',{name:'Bevindingen',exact:true}).waitFor();await noOverflow('issues');if(data.findings.length){await page.locator('#filter-second').selectOption(data.findings[0].severity);assert(await page.locator('#results .issue').count()>0);await page.goto('https://review.test/#issue/'+data.findings[0].id);await page.locator('.review').waitFor();await noOverflow('finding detail');}
await page.goto('https://review.test/#method');await page.getByRole('heading',{name:'Methode & bestanden'}).waitFor();await noOverflow('method');await page.goto('https://review.test/#page/not-a-page');await page.getByRole('heading',{name:'Niet beschikbaar'}).waitFor();await noOverflow('missing deep link');
await page.goto('https://review.test/#review');
if(!data.publication_gate?.ready){await page.getByRole('heading',{name:'Review nog niet vrijgegeven'}).waitFor();checks.push(`${width}px publication gate visible`)}
const firstDetail=JSON.parse(fs.readFileSync(path.join(root,p.detail)));
const realQueue=data.review_queue||[];
const testCases=realQueue.length>=3?realQueue.slice(0,3):firstDetail.units.filter(u=>u.crop&&u.bbox).slice(0,3).map((u,i)=>({id:'QA-'+i,page_id:p.id,region_ids:[u.id],pipeline_version:'qa-fixture-only',question:'[QA] Klopt dit voorstel voor regio '+u.id+'?',what_good_means:'De gemarkeerde regio klopt.',what_bad_means:'De gemarkeerde regio klopt niet.',crop:u.crop,source:p.image.source,context:p.image.preview,bbox:u.bbox,category:'Broncontrole'}));
assert.equal(testCases.length,3);
queueFixture={...data,publication_gate:{ready:true},review_queue:testCases,pipeline_version:testCases[0].pipeline_version};
await page.reload();await page.locator('[data-case-id]').waitFor();assert.equal(await page.locator('[data-case-id]').getAttribute('data-case-id'),testCases[0].id);await noOverflow('decision queue');
if(width===390)await page.screenshot({path:path.join(out,'mobile-decision.png'),fullPage:true});
await page.getByRole('button',{name:'Hele pagina',exact:true}).click();assert.equal(await page.locator('#case-context').getAttribute('hidden'),null);await page.getByRole('button',{name:'Broncrop',exact:true}).click();
await page.getByRole('button',{name:'GOED ✓',exact:true}).click();await page.waitForFunction(id=>document.querySelector('[data-case-id]')?.dataset.caseId===id,testCases[1].id);await page.getByRole('button',{name:'FOUT ×',exact:true}).click();await page.waitForFunction(id=>document.querySelector('[data-case-id]')?.dataset.caseId===id,testCases[2].id);await page.getByRole('button',{name:'Overslaan',exact:true}).click();await page.getByRole('heading',{name:'Je antwoorden zijn klaar om te delen'}).waitFor();await page.reload();await page.getByRole('heading',{name:'Je antwoorden zijn klaar om te delen'}).waitFor();
const answerDownloadPromise=page.waitForEvent('download');await page.locator('#export').click();const answerDownload=await answerDownloadPromise;const answerFile=path.join(out,`answers-${width}.json`);await answerDownload.saveAs(answerFile);const response=JSON.parse(fs.readFileSync(answerFile));assert.deepEqual(response.answers.map(x=>x.decision),['good','bad','skip']);assert(response.answers.every(x=>x.case_id&&x.page_id&&x.region_ids.length&&x.pipeline_version&&x.answered_at));checks.push(`${width}px GOOD/BAD/SKIP, auto-next, persistent answers, share/download metadata`);
await page.getByRole('button',{name:'Bekijk overgeslagen gevallen'}).click();await page.locator('[data-case-id]').waitFor();assert.equal(await page.locator('[data-case-id]').getAttribute('data-case-id'),testCases[2].id);
await context.close();sources=[];}
assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);await browser.close();fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({tested_at:new Date().toISOString(),pages:data.pages.length,findings:data.findings.length,queue_content_source:(data.review_queue?.length>=3?'provided review queue':'explicit in-memory QA fixture on real crops'),publication_gate:data.publication_gate||null,checks,errors,missing},null,2));console.log(JSON.stringify({checks:checks.length,errors,missing,findings:data.findings.length,out}));})().catch(e=>{console.error(e);process.exit(1)});
