const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const crypto=require('node:crypto');const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');
const root=path.resolve(process.env.SITE_ROOT||path.join(__dirname,'../site')),out=path.resolve(process.env.QA_OUTPUT||path.join(__dirname,'../qa'));fs.mkdirSync(out,{recursive:true});
function fingerprint(){const files=[];function walk(dir){for(const item of fs.readdirSync(dir,{withFileTypes:true})){if(['.git','.github','tests','node_modules','qa-results','.gitignore'].includes(item.name))continue;const file=path.join(dir,item.name);if(item.isDirectory())walk(file);else files.push(file)}}walk(root);const hash=crypto.createHash('sha256');for(const file of files.sort()){hash.update(path.relative(root,file).split(path.sep).join('/')+'\0');hash.update(crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex')+'\n')}return hash.digest('hex')};
(async()=>{const initialFingerprint=fingerprint();const browser=await chromium.launch({headless:true,...(process.env.CHROME_EXECUTABLE?{executablePath:process.env.CHROME_EXECUTABLE}:{})});const data=JSON.parse(fs.readFileSync(path.join(root,'data/index.json')));let checks=[],errors=[],missing=[],sources=[];
for(const width of [360,390,430]){const context=await browser.newContext({viewport:{width,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1,acceptDownloads:true});
let queueFixture=null;await context.route('**/*',async route=>{const url=new URL(route.request().url());let name=decodeURIComponent(url.pathname).replace(/^\//,'')||'index.html';if(name==='favicon.ico')return route.fulfill({status:204});if(name==='data/index.json'&&queueFixture)return route.fulfill({status:200,json:queueFixture});let file=path.resolve(root,name);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){missing.push(name);return route.fulfill({status:404,body:'missing'})}if(name.startsWith('media/source/'))sources.push(name);return route.fulfill({status:200,path:file,contentType:({'.html':'text/html','.css':'text/css','.js':'text/javascript','.json':'application/json','.jpg':'image/jpeg','.md':'text/markdown'})[path.extname(file)]||'application/octet-stream'})});
const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));const noOverflow=async(label)=>{const result=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert(result.scroll<=result.width,`${label}: horizontal overflow ${JSON.stringify(result)}`);checks.push(`${width}px ${label}: no overflow`)};
await page.goto('https://review.test/#overview');await page.getByRole('heading',{name:'Van krant naar inhoud'}).waitFor();await noOverflow('overview');assert.equal(sources.length,0,'full sources must not load on overview');if(width===390)await page.screenshot({path:path.join(out,'mobile-overview.png'),fullPage:true});
await page.getByRole('link',{name:'Edities',exact:true}).click();await page.locator('#results .card').first().waitFor();await noOverflow('editions');await page.locator('#filter-title').selectOption({label:data.editions[0].title});assert(await page.locator('#results .card').count()>0);await page.locator('#filter-text').fill('nonexistent-qa-query');await page.getByText('Geen edities met deze filters.').waitFor();await page.locator('#filter-text').fill('');
const p=data.pages.find(x=>x.units_count>0);await page.goto('https://review.test/#page/'+p.id);await page.getByRole('heading',{name:'Pagina '+p.page_number,exact:true}).waitFor();await page.locator('.viewer img').waitFor();await page.waitForFunction(()=>{const i=document.querySelector('.viewer img');return i?.complete&&i.naturalWidth>0});assert(await page.locator('.viewer img').evaluate(i=>i.complete&&i.naturalWidth>0));await noOverflow('page');assert.deepEqual(await page.locator('.page-numbers a').allTextContents(),data.pages.filter(x=>x.edition_id===p.edition_id).sort((a,b)=>a.page_number-b.page_number).map(x=>String(x.page_number)));checks.push(`${width}px edition page order`);await page.getByRole('button',{name:/Toon regio/}).click();assert.equal(await page.locator('#regions-overlay').getAttribute('hidden'),null);await page.getByRole('button',{name:/Toon regio/}).click();assert.notEqual(await page.locator('#regions-overlay').getAttribute('hidden'),null);await page.getByRole('button',{name:'Probleem',exact:true}).click();await page.locator('[data-note]').fill('QA-notitie: bron en OCR vergeleken.');await page.reload();await page.locator('[data-note]').waitFor();assert.equal(await page.locator('[data-note]').inputValue(),'QA-notitie: bron en OCR vergeleken.');assert.equal(await page.getByRole('button',{name:'Probleem',exact:true}).getAttribute('aria-pressed'),'true');checks.push(`${width}px persistentie reviewstatus + notitie`);
if(width===390)await page.screenshot({path:path.join(out,'mobile-page.png'),fullPage:true});
const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Deel antwoorden'}).click();const download=await downloadPromise;const save=path.join(out,`review-${width}.json`);await download.saveAs(save);const exported=JSON.parse(fs.readFileSync(save));assert(Object.values(exported.page_issue_notes).some(v=>v.note==='QA-notitie: bron en OCR vergeleken.'&&v.status==='problem'));checks.push(`${width}px JSON-export geverifieerd`);
await page.locator('.unit summary').first().click();const crop=page.locator('.unit-content .image-button').first();await crop.click();await page.locator('dialog[open]').waitFor();await page.waitForFunction(()=>{let x=document.getElementById('zoom-image');return x.complete&&x.naturalWidth>0});await noOverflow('zoom');await page.getByRole('button',{name:'Inzoomen',exact:true}).click();assert.equal(await page.locator('#zoom-image').evaluate(i=>i.style.width),'160%');await page.getByRole('button',{name:'Sluiten ×'}).click();checks.push(`${width}px source crop zoom + overlay`);
await page.goto('https://review.test/#issues');await page.getByRole('heading',{name:'Bevindingen',exact:true}).waitFor();await noOverflow('issues');if(data.findings.length){await page.locator('#filter-second').selectOption(data.findings[0].severity);assert(await page.locator('#results .issue').count()>0);await page.goto('https://review.test/#issue/'+data.findings[0].id);await page.locator('.review').waitFor();await noOverflow('finding detail');await page.getByRole('link',{name:'Bekijk bron en uitvoer'}).click();await page.locator('.issue-box').waitFor();assert.equal(await page.locator('#regions-overlay').getAttribute('hidden'),null);checks.push(`${width}px finding-to-source marker`);}
const partial=data.pages.find(x=>!x.units_count);if(partial){await page.goto('https://review.test/#page/'+partial.id);await page.getByText('Nog geen inhoudseenheden voor deze pagina.').waitFor();await noOverflow('partial page');checks.push(`${width}px actual partial data`)}await page.goto('https://review.test/#method');await page.getByRole('heading',{name:'Methode & bestanden'}).waitFor();await noOverflow('method');await page.goto('https://review.test/#page/not-a-page');await page.getByRole('heading',{name:'Niet beschikbaar'}).waitFor();await noOverflow('missing deep link');
await page.goto('https://review.test/#review');
if(!data.publication_gate?.ready){await page.getByRole('heading',{name:'Review nog niet vrijgegeven'}).waitFor();checks.push(`${width}px publication gate visible`)}
const firstDetail=JSON.parse(fs.readFileSync(path.join(root,p.detail)));
const realQueue=data.review_queue||[];
const testCases=realQueue.length?realQueue:firstDetail.units.filter(u=>u.crop&&u.bbox).slice(0,3).map((u,i)=>({id:'QA-'+i,page_id:p.id,region_ids:[u.id],pipeline_version:'qa-fixture-only',question:'[QA] Klopt dit voorstel voor regio '+u.id+'?',what_good_means:'De gemarkeerde regio klopt.',what_bad_means:'De gemarkeerde regio klopt niet.',crop:u.crop,source:p.image.source,context:p.image.preview,bbox:u.bbox,category:'Broncontrole'}));
assert(testCases.length>0);
queueFixture={...data,publication_gate:{ready:true},review_queue:testCases,pipeline_version:testCases[0].pipeline_version};
await page.reload();await page.locator('[data-case-id]').waitFor();assert.equal(await page.locator('[data-case-id]').getAttribute('data-case-id'),testCases[0].id);await noOverflow('decision queue');await page.waitForFunction(()=>{const i=document.querySelector('#case-crop img');return i?.complete&&i.naturalWidth>0});
if(width===390)await page.screenshot({path:path.join(out,'mobile-decision.png'),fullPage:true});
await page.getByRole('button',{name:'Hele pagina',exact:true}).click();assert.equal(await page.locator('#case-context').getAttribute('hidden'),null);await page.getByRole('button',{name:'Broncrop',exact:true}).click();if(testCases[0].overlay){await page.getByRole('button',{name:'Voorstel met kaders',exact:true}).click();await page.waitForFunction(()=>{const i=document.querySelector('#case-overlay img');return i?.complete&&i.naturalWidth>0});await page.getByRole('button',{name:'Broncrop',exact:true}).click()}for(const img of await page.locator('.case-comparisons > section > button > img').all()){await img.scrollIntoViewIfNeeded();await img.evaluate(i=>i.decode())}checks.push(`${width}px queue crop/context and supplied comparison images`);
const actions=testCases.map((_,i)=>[['GOED ✓','good'],['FOUT ×','bad'],['Overslaan','skip']][i%3]);
for(let i=0;i<actions.length;i++){await noOverflow('case '+testCases[i].id);for(const img of await page.locator('#case-crop img,.case-comparisons > section > button > img,.case-comparisons .physical-part img').all()){await img.scrollIntoViewIfNeeded();await img.evaluate(i=>i.decode())}await page.getByRole('button',{name:actions[i][0],exact:true}).click();if(i+1<testCases.length)await page.waitForFunction(id=>document.querySelector('[data-case-id]')?.dataset.caseId===id,testCases[i+1].id)}
await page.getByRole('heading',{name:'Je antwoorden zijn klaar om te delen'}).waitFor();await page.reload();await page.getByRole('heading',{name:'Je antwoorden zijn klaar om te delen'}).waitFor();
const answerDownloadPromise=page.waitForEvent('download');await page.locator('#export').click();const answerDownload=await answerDownloadPromise;const answerFile=path.join(out,`answers-${width}.json`);await answerDownload.saveAs(answerFile);const response=JSON.parse(fs.readFileSync(answerFile));assert.deepEqual(response.answers.map(x=>x.decision),actions.map(x=>x[1]));assert(response.answers.every(x=>x.case_id&&x.page_id&&x.region_ids.length&&x.pipeline_version&&x.answered_at));assert(response.answers.every(x=>Array.isArray(x.comparisons)));for(let i=0;i<testCases.length;i++)assert.equal(response.answers[i].comparisons.length,(testCases[i].comparisons||[]).length);checks.push(`${width}px GOOD/BAD/SKIP, auto-next, persistent answers, share/download metadata`);
await page.evaluate(()=>{Object.defineProperty(navigator,'canShare',{configurable:true,value:payload=>payload.files?.length===1});Object.defineProperty(navigator,'share',{configurable:true,value:async payload=>{window.__sharedAnswer={title:payload.title,name:payload.files[0].name,type:payload.files[0].type,text:await payload.files[0].text()}}})});await page.locator('#export').click();await page.waitForFunction(()=>Boolean(window.__sharedAnswer));const shared=await page.evaluate(()=>window.__sharedAnswer);assert.equal(shared.type,'application/json');assert.deepEqual(JSON.parse(shared.text).answers,response.answers);checks.push(`${width}px supported Web Share file payload`);
await page.goto('https://review.test/#case/not-a-case');await page.getByRole('heading',{name:'Niet beschikbaar'}).waitFor();checks.push(`${width}px invalid review case deep link`);await page.goto('https://review.test/#review');
if(testCases.length>=3){await page.getByRole('button',{name:'Bekijk overgeslagen gevallen'}).click();await page.locator('[data-case-id]').waitFor();assert.equal(await page.locator('[data-case-id]').getAttribute('data-case-id'),testCases[2].id)}
await context.close();sources=[];}
assert.equal(fingerprint(),initialFingerprint,'Site changed during QA');assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);await browser.close();fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({tested_at:new Date().toISOString(),source_fingerprint:initialFingerprint,pages:data.pages.length,findings:data.findings.length,tested_queue_cases:data.review_queue?.length||3,provided_queue_cases:data.review_queue?.length||0,queue_content_source:(data.review_queue?.length>0?'provided review queue':'explicit in-memory QA fixture on real crops'),publication_gate:data.publication_gate||null,checks,errors,missing},null,2));console.log(JSON.stringify({checks:checks.length,errors,missing,findings:data.findings.length,out}));})().catch(e=>{console.error(e);process.exit(1)});
